new.py:92: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:178: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:221: RuntimeWarning: invalid value encountered in greater
  a = (data1_t[i][2] > thres_distance)*1
2017-12-01 17:36:13.820213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Found device 0 with properties: 
name: Tesla K40t major: 3 minor: 5 memoryClockRate(GHz): 0.8755
pciBusID: 0000:82:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2017-12-01 17:36:13.820243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K40t, pci bus id: 0000:82:00.0, compute capability: 3.5)
=>> PBS: job killed: walltime 82882 exceeded limit 82800
