Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
new.py:113: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:214: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:254: RuntimeWarning: invalid value encountered in greater
  a = (data1_t[i][2] > thres_distance)*1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K40t
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:82:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40t, pci bus id: 0000:82:00.0)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1887 get requests, put_count=1744 evicted_count=1000 eviction_rate=0.573394 and unsatisfied allocation rate=0.658718
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 3145 get requests, put_count=3043 evicted_count=1000 eviction_rate=0.328623 and unsatisfied allocation rate=0.357711
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
=>> PBS: job killed: walltime 36096 exceeded limit 36000
