new.py:129: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:261: RuntimeWarning: invalid value encountered in greater
  a = (data1_t[i][2] > thres_distance)*1
2017-12-14 21:54:57.736022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Found device 0 with properties: 
name: Tesla K40t major: 3 minor: 5 memoryClockRate(GHz): 0.8755
pciBusID: 0000:82:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2017-12-14 21:54:57.736052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K40t, pci bus id: 0000:82:00.0, compute capability: 3.5)
